[build]
builder = "nixpacks"

[build.nixpacks]
plan = '''
  [phases.setup]
  nixPkgs = ["nodejs_18"]

  [phases.install]
  cmds = ["npm install"]

  [phases.build]
  cmds = ["npm run build"]

  [phases.start]
  cmds = ["npm run start"]
'''

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10