
[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --omit=dev"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmds = ["npm run start"]