import { Request, Response } from 'express';
import { PrismaClient } from '@prisma/client';
import PdfPrinter from 'pdfmake';

const prisma = new PrismaClient();

// Configure PDFMake with Helvetica only
const fonts = {
  Helvetica: {
    normal: 'Helvetica',
    bold: 'Helvetica-Bold',
    italics: 'Helvetica-Oblique',
    bolditalics: 'Helvetica-BoldOblique'
  }
};
const printer = new PdfPrinter(fonts);

// Default font for all text
const DEFAULT_FONT = 'Helvetica';

// Color Palette
const COLORS = {
  primary: '#2563EB',
  primaryLight: '#EFF6FF',
  primaryDark: '#1D4ED8',
  success: '#16A34A',
  danger: '#DC2626',
  warning: '#F59E0B',
  gray: '#64748B',
  grayLight: '#F1F5F9',
  grayDark: '#1E293B',
  white: '#FFFFFF',
};

// Helper: Format date
function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

// Helper: Format time
function formatTime(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  });
}

// Helper: Format enum
function formatEnum(value: string): string {
  if (!value) return '';
  return value
    .toLowerCase()
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

// Helper: Format status
function formatStatus(status: string): string {
  return formatEnum(status);
}

// Helper: Create text with default font
function t(text: string, options: any = {}): any {
  return {
    text,
    font: DEFAULT_FONT,
    ...options
  };
}

// Helper: Create header
function createHeader(): any {
  return {
    table: {
      widths: ['*'],
      body: [
        [
          {
            stack: [
              t('EDUALLOC', { fontSize: 22, bold: true, color: COLORS.white }),
              t('Course Allocation Management System', { fontSize: 10, color: COLORS.white }),
            ],
            fillColor: COLORS.primary,
            margin: [20, 18],
            alignment: 'center',
          },
        ],
      ],
    },
    layout: 'noBorders',
  };
}

// Helper: Create title
function createReportTitle(title: string): any {
  return t(title, {
    fontSize: 20,
    bold: true,
    color: COLORS.grayDark,
    alignment: 'center',
    margin: [0, 20, 0, 16],
  });
}

// Helper: Create info card
function createInfoCard(data: {
  generatedAt: string;
  reportType: string;
  generatedBy: string;
  totalRecords: number;
  extra?: { label: string; value: string }[];
}): any {
  const rows = [
    ['Generated On', `${formatDate(data.generatedAt)} at ${formatTime(data.generatedAt)}`],
    ['Report Type', data.reportType],
    ['Generated By', data.generatedBy],
    ['Total Records', String(data.totalRecords)],
  ];

  if (data.extra) {
    for (const item of data.extra) {
      rows.push([item.label, item.value]);
    }
  }

  return {
    table: {
      widths: ['auto', '*'],
      body: [
        [
          {
            text: 'Report Information',
            colSpan: 2,
            bold: true,
            fontSize: 12,
            color: COLORS.primary,
            margin: [0, 0, 0, 6],
            font: DEFAULT_FONT,
          },
          {},
        ],
        ...rows.map(row => [
          { text: row[0], bold: true, color: COLORS.gray, fontSize: 10, font: DEFAULT_FONT },
          { text: row[1], color: COLORS.grayDark, fontSize: 10, font: DEFAULT_FONT },
        ]),
      ],
    },
    layout: 'lightHorizontalLines',
    margin: [0, 0, 0, 16],
  };
}

// Helper: Create stats cards
function createStatsCards(stats: { label: string; value: string; color?: string }[]): any {
  const cardWidth = 100 / stats.length;
  
  const body = stats.map(stat => ({
    text: stat.value,
    fontSize: 18,
    bold: true,
    color: stat.color || COLORS.primary,
    alignment: 'center',
    font: DEFAULT_FONT,
  }));

  const labels = stats.map(stat => ({
    text: stat.label,
    fontSize: 9,
    color: COLORS.gray,
    alignment: 'center',
    margin: [0, 2, 0, 0],
    font: DEFAULT_FONT,
  }));

  return {
    table: {
      widths: stats.map(() => `${cardWidth}%`),
      body: [
        body.map((item) => ({
          ...item,
          margin: [0, 8, 0, 0],
          fillColor: COLORS.primaryLight,
        })),
        labels.map((item) => ({
          ...item,
          fillColor: COLORS.primaryLight,
          margin: [0, 0, 0, 8],
        })),
      ],
    },
    layout: {
      fillColor: () => COLORS.primaryLight,
      padding: [4, 4, 4, 4],
    },
    margin: [0, 0, 0, 16],
  };
}

// Helper: Create table with alternating colors
function createTable(columns: string[], rows: any[][], columnWidths: string[]): any {
  const headerRow = columns.map(text => ({
    text,
    bold: true,
    color: COLORS.white,
    fillColor: COLORS.primary,
    padding: [8, 6, 8, 6],
    fontSize: 10,
    font: DEFAULT_FONT,
  }));

  return {
    table: {
      headerRows: 1,
      widths: columnWidths,
      body: [
        headerRow,
        ...rows.map((row, rowIndex) => 
          row.map(cell => ({
            text: cell,
            fontSize: 9,
            padding: [6, 4, 6, 4],
            color: COLORS.grayDark,
            fillColor: rowIndex % 2 === 0 ? COLORS.grayLight : COLORS.white,
            font: DEFAULT_FONT,
          }))
        ),
      ],
    },
    layout: {
      fillColor: (rowIndex: number) => {
        if (rowIndex === 0) return COLORS.primary;
        return rowIndex % 2 === 0 ? COLORS.grayLight : COLORS.white;
      },
      hLineColor: () => COLORS.grayLight,
      vLineColor: () => COLORS.grayLight,
    },
    margin: [0, 0, 0, 16],
  };
}

// Helper: Create footer
function createFooter(currentPage: number, pageCount: number): any {
  return {
    columns: [
      {
        text: 'EduAlloc • Course Allocation Management System',
        fontSize: 8,
        color: COLORS.gray,
        alignment: 'left',
        font: DEFAULT_FONT,
      },
      {
        text: `Page ${currentPage} of ${pageCount}`,
        fontSize: 8,
        color: COLORS.gray,
        alignment: 'right',
        font: DEFAULT_FONT,
      },
    ],
    margin: [35, 10, 35, 20],
  };
}

export class ReportController {
  async generateAllocationReport(req: Request, res: Response) {
    try {
      const { lecturerId } = req.body;
      
      const whereClause: any = {};
      if (lecturerId) {
        whereClause.lecturerId = parseInt(lecturerId);
      }

      const allocations = await prisma.allocation.findMany({
        where: {
          ...whereClause,
          status: { in: ['AUTO_ALLOCATED', 'APPROVED', 'OVERRIDDEN'] }
        },
        include: {
          lecturer: true,
          course: true
        }
      });

      const scores = allocations.map(a => a.score).filter(s => s !== null) as number[];
      const totalScore = scores.reduce((sum, s) => sum + s, 0);
      const avgScore = scores.length > 0 ? (totalScore / scores.length) : 0;
      const highestScore = scores.length > 0 ? Math.max(...scores) : 0;
      const lowestScore = scores.length > 0 ? Math.min(...scores) : 0;

      const reportData = {
        generatedAt: new Date().toISOString(),
        type: 'allocation',
        totalAllocations: allocations.length,
        allocations: allocations.map(a => ({
          lecturer: a.lecturer.name,
          lecturerStaffId: a.lecturer.staffId,
          course: `${a.course.code} - ${a.course.title}`,
          units: a.course.units,
          status: a.status,
          score: a.score
        })),
        avgScore,
        highestScore,
        lowestScore,
      };

      const report = await prisma.report.create({
        data: {
          generatedBy: 'System',
          reportType: 'ALLOCATION_REPORT',
          data: JSON.stringify(reportData)
        }
      });

      return res.json({ success: true, data: report });
    } catch (error) {
      return res.status(500).json({ success: false, error: (error as Error).message });
    }
  }

  async generateWorkloadSummary(_req: Request, res: Response) {
    try {
      const lecturers = await prisma.lecturer.findMany({
        where: { isActive: true },
        include: {
          allocations: {
            where: {
              status: { in: ['AUTO_ALLOCATED', 'APPROVED', 'OVERRIDDEN'] }
            },
            include: { course: true }
          }
        }
      });

      const summary = lecturers.map(l => {
        const totalLoad = l.allocations.reduce((sum, a) => sum + a.course.units, 0);
        return {
          name: l.name,
          staffId: l.staffId,
          rank: l.rank,
          currentLoad: totalLoad,
          maxLoad: l.maxHours,
          utilization: Math.round((totalLoad / l.maxHours) * 100),
          courses: l.allocations.map(a => ({
            code: a.course.code,
            title: a.course.title,
            units: a.course.units
          }))
        };
      });

      const loads = summary.map(s => s.currentLoad);
      const totalLecturers = lecturers.length;
      const avgLoad = loads.length > 0 ? (loads.reduce((sum, l) => sum + l, 0) / loads.length) : 0;
      const highestLoad = loads.length > 0 ? Math.max(...loads) : 0;
      const lowestLoad = loads.length > 0 ? Math.min(...loads) : 0;

      const reportData = {
        generatedAt: new Date().toISOString(),
        type: 'workload',
        totalLecturers,
        summary,
        avgLoad,
        highestLoad,
        lowestLoad,
      };

      const report = await prisma.report.create({
        data: {
          generatedBy: 'System',
          reportType: 'WORKLOAD_SUMMARY',
          data: JSON.stringify(reportData)
        }
      });

      return res.json({ success: true, data: report });
    } catch (error) {
      return res.status(500).json({ success: false, error: (error as Error).message });
    }
  }

  async generateLevelBasedList(req: Request, res: Response) {
    try {
      const { level } = req.body;
      const levelNum = parseInt(level);

      const courses = await prisma.course.findMany({
        where: { 
          level: levelNum,
          status: true
        },
        include: {
          allocations: {
            where: {
              status: { in: ['AUTO_ALLOCATED', 'APPROVED', 'OVERRIDDEN'] }
            },
            include: { lecturer: true }
          }
        }
      });

      const levelData = courses.map(c => ({
        code: c.code,
        title: c.title,
        units: c.units,
        nature: c.nature,
        allocatedTo: c.allocations.length > 0 ? c.allocations[0].lecturer.name : 'Not Allocated',
        status: c.allocations.length > 0 ? 'Allocated' : 'Unallocated'
      }));

      const totalCourses = courses.length;
      const allocated = levelData.filter(c => c.status === 'Allocated').length;
      const unallocated = levelData.filter(c => c.status === 'Unallocated').length;

      const reportData = {
        generatedAt: new Date().toISOString(),
        type: 'level',
        level: levelNum,
        totalCourses,
        allocated,
        unallocated,
        allocationRate: totalCourses > 0 ? Math.round((allocated / totalCourses) * 100) : 0,
        courses: levelData
      };

      const report = await prisma.report.create({
        data: {
          generatedBy: 'System',
          reportType: 'LEVEL_BASED_LIST',
          data: JSON.stringify(reportData)
        }
      });

      return res.json({ success: true, data: report });
    } catch (error) {
      return res.status(500).json({ success: false, error: (error as Error).message });
    }
  }

  async getAll(_req: Request, res: Response) {
    try {
      const reports = await prisma.report.findMany({
        orderBy: { generatedAt: 'desc' }
      });
      return res.json({ success: true, data: reports });
    } catch (error) {
      return res.status(500).json({ success: false, error: (error as Error).message });
    }
  }

  async getById(req: Request, res: Response) {
    try {
      const id = parseInt(req.params.id);
      const report = await prisma.report.findUnique({
        where: { id }
      });
      if (!report) {
        return res.status(404).json({ success: false, error: 'Report not found' });
      }
      return res.json({ success: true, data: report });
    } catch (error) {
      return res.status(500).json({ success: false, error: (error as Error).message });
    }
  }

  async exportToPDF(req: Request, res: Response) {
    try {
      const id = parseInt(req.params.id);
      const report = await prisma.report.findUnique({
        where: { id }
      });
      if (!report) {
        return res.status(404).json({ success: false, error: 'Report not found' });
      }

      const reportData = typeof report.data === 'string' ? JSON.parse(report.data) : report.data;

      let pdfDoc: any;
      let filename: string;

      switch (report.reportType) {
        case 'ALLOCATION_REPORT':
          pdfDoc = this.generateAllocationPDF(reportData);
          filename = `allocation-report-${report.id}.pdf`;
          break;
        case 'WORKLOAD_SUMMARY':
          pdfDoc = this.generateWorkloadPDF(reportData);
          filename = `workload-summary-${report.id}.pdf`;
          break;
        case 'LEVEL_BASED_LIST':
          pdfDoc = this.generateLevelPDF(reportData);
          filename = `level-based-list-${report.id}.pdf`;
          break;
        default:
          throw new Error('Unknown report type');
      }

      const pdfBuffer = await new Promise<Buffer>((resolve) => {
        const pdfDocGenerator = printer.createPdfKitDocument(pdfDoc);
        const chunks: any[] = [];
        pdfDocGenerator.on('data', (chunk) => chunks.push(chunk));
        pdfDocGenerator.on('end', () => {
          resolve(Buffer.concat(chunks));
        });
        pdfDocGenerator.end();
      });

      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
      res.setHeader('Content-Length', pdfBuffer.length);
      
      return res.send(pdfBuffer);
    } catch (error) {
      console.error('PDF Export Error:', error);
      return res.status(500).json({ success: false, error: (error as Error).message });
    }
  }

  private generateAllocationPDF(data: any) {
    const tableData = data.allocations.map((a: any, index: number) => [
      String(index + 1),
      a.lecturer,
      a.lecturerStaffId || '-',
      a.course,
      String(a.units),
      formatStatus(a.status),
      a.score ? a.score.toFixed(2) : '-'
    ]);

    return {
      pageSize: 'A4',
      pageMargins: [35, 55, 35, 55],
      defaultStyle: {
        font: DEFAULT_FONT,
      },
      content: [
        createHeader(),
        createReportTitle('COURSE ALLOCATION REPORT'),
        createInfoCard({
          generatedAt: data.generatedAt,
          reportType: 'Allocation Report',
          generatedBy: 'System',
          totalRecords: data.totalAllocations,
          extra: [
            { label: 'Average Score', value: data.avgScore ? data.avgScore.toFixed(2) : 'N/A' },
            { label: 'Highest Score', value: data.highestScore ? data.highestScore.toFixed(2) : 'N/A' },
            { label: 'Lowest Score', value: data.lowestScore ? data.lowestScore.toFixed(2) : 'N/A' },
          ]
        }),
        createStatsCards([
          { label: 'Total Allocations', value: String(data.totalAllocations), color: COLORS.primary },
          { label: 'Average Score', value: data.avgScore ? data.avgScore.toFixed(2) : 'N/A', color: COLORS.success },
          { label: 'Highest Score', value: data.highestScore ? data.highestScore.toFixed(2) : 'N/A', color: COLORS.warning },
        ]),
        createTable(
          ['#', 'Lecturer', 'Staff ID', 'Course', 'Units', 'Status', 'Score'],
          tableData,
          ['auto', 'auto', 'auto', '*', 'auto', 'auto', 'auto']
        ),
        { text: '', margin: [0, 20, 0, 0] },
      ],
      footer: (currentPage: number, pageCount: number) => createFooter(currentPage, pageCount),
    };
  }

  private generateWorkloadPDF(data: any) {
    const tableData = data.summary.map((s: any, index: number) => [
      String(index + 1),
      s.name,
      s.staffId,
      formatEnum(s.rank),
      String(s.currentLoad),
      String(s.maxLoad),
      `${s.utilization}%`
    ]);

    return {
      pageSize: 'A4',
      pageMargins: [35, 55, 35, 55],
      defaultStyle: {
        font: DEFAULT_FONT,
      },
      content: [
        createHeader(),
        createReportTitle('WORKLOAD SUMMARY REPORT'),
        createInfoCard({
          generatedAt: data.generatedAt,
          reportType: 'Workload Summary',
          generatedBy: 'System',
          totalRecords: data.totalLecturers,
          extra: [
            { label: 'Average Load', value: data.avgLoad ? data.avgLoad.toFixed(1) + ' hrs' : 'N/A' },
            { label: 'Highest Load', value: data.highestLoad ? data.highestLoad + ' hrs' : 'N/A' },
            { label: 'Lowest Load', value: data.lowestLoad ? data.lowestLoad + ' hrs' : 'N/A' },
          ]
        }),
        createStatsCards([
          { label: 'Total Lecturers', value: String(data.totalLecturers), color: COLORS.primary },
          { label: 'Average Load', value: data.avgLoad ? data.avgLoad.toFixed(1) + ' hrs' : 'N/A', color: COLORS.success },
          { label: 'Max Load', value: data.highestLoad ? data.highestLoad + ' hrs' : 'N/A', color: COLORS.warning },
        ]),
        createTable(
          ['#', 'Lecturer', 'Staff ID', 'Rank', 'Current Load', 'Max Load', 'Utilization'],
          tableData,
          ['auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto']
        ),
        { text: '', margin: [0, 20, 0, 0] },
      ],
      footer: (currentPage: number, pageCount: number) => createFooter(currentPage, pageCount),
    };
  }

  private generateLevelPDF(data: any) {
    const tableData = data.courses.map((c: any, index: number) => [
      String(index + 1),
      c.code,
      c.title,
      String(c.units),
      formatEnum(c.nature),
      c.allocatedTo,
      c.status
    ]);

    return {
      pageSize: 'A4',
      pageMargins: [35, 55, 35, 55],
      defaultStyle: {
        font: DEFAULT_FONT,
      },
      content: [
        createHeader(),
        createReportTitle(`LEVEL ${data.level} - COURSE LIST`),
        createInfoCard({
          generatedAt: data.generatedAt,
          reportType: ` ${data.level} Level Course List`,
          generatedBy: 'System',
          totalRecords: data.totalCourses,
          extra: [
            { label: 'Allocated', value: String(data.allocated) },
            { label: 'Unallocated', value: String(data.unallocated) },
            { label: 'Allocation Rate', value: `${data.allocationRate}%` },
          ]
        }),
        createStatsCards([
          { label: 'Total Courses', value: String(data.totalCourses), color: COLORS.primary },
          { label: 'Allocated', value: String(data.allocated), color: COLORS.success },
          { label: 'Allocation %', value: `${data.allocationRate}%`, color: data.allocationRate > 80 ? COLORS.success : COLORS.warning },
        ]),
        createTable(
          ['#', 'Course Code', 'Course Title', 'Units', 'Nature', 'Allocated To', 'Status'],
          tableData,
          ['auto', 'auto', '*', 'auto', 'auto', '*', 'auto']
        ),
        { text: '', margin: [0, 20, 0, 0] },
      ],
      footer: (currentPage: number, pageCount: number) => createFooter(currentPage, pageCount),
    };
  }
}