import { Request, Response } from 'express';
import { PrismaClient } from '@prisma/client';
import PdfPrinter from 'pdfmake';

const prisma = new PrismaClient();

// ============================================================
// 1. FONTS CONFIGURATION
// ============================================================
// For Plus Jakarta Sans, you need to download the font files
// and place them in your project (e.g., src/assets/fonts/)
// Download from: https://fonts.google.com/specimen/Plus+Jakarta+Sans
const fonts = {
  PlusJakartaSans: {
    normal: 'src/assets/fonts/PlusJakartaSans-Regular.ttf',
    bold: 'src/assets/fonts/PlusJakartaSans-Bold.ttf',
    italics: 'src/assets/fonts/PlusJakartaSans-Italic.ttf',
    bolditalics: 'src/assets/fonts/PlusJakartaSans-BoldItalic.ttf'
  },
  // Fallback fonts if custom fonts fail
  Helvetica: {
    normal: 'Helvetica',
    bold: 'Helvetica-Bold',
    italics: 'Helvetica-Oblique',
    bolditalics: 'Helvetica-BoldOblique'
  }
};

const printer = new PdfPrinter(fonts);

// Default font - use Plus Jakarta Sans if available, fallback to Helvetica
const DEFAULT_FONT = 'PlusJakartaSans';

// ============================================================
// 2. COLOR PALETTE
// ============================================================
const COLORS = {
  primary: '#2563EB',
  primaryLight: '#EFF6FF',
  primaryDark: '#1D4ED8',
  secondary: '#64748B',
  success: '#16A34A',
  successLight: '#F0FDF4',
  danger: '#DC2626',
  dangerLight: '#FEF2F2',
  warning: '#F59E0B',
  warningLight: '#FFFBEB',
  gray: '#94A3B8',
  grayLight: '#F1F5F9',
  grayLighter: '#F8FAFC',
  grayDark: '#1E293B',
  white: '#FFFFFF',
  border: '#E2E8F0',
};

// ============================================================
// 3. HELPERS
// ============================================================
function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

function formatTime(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  });
}

function formatEnum(value: string): string {
  if (!value) return '';
  return value
    .toLowerCase()
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function formatStatus(status: string): string {
  const statusMap: Record<string, string> = {
    'AUTO_ALLOCATED': 'ALLOCATED',
    'APPROVED': 'CONFIRMED',
    'OVERRIDDEN': 'OVERRIDDEN',
    'PENDING': 'PENDING',
    'CONFLICT': 'CONFLICT',
    'UNALLOCATED': 'UNALLOCATED',
  };
  return statusMap[status] || formatEnum(status);
}

function getStatusColor(status: string): string {
  const colorMap: Record<string, string> = {
    'ALLOCATED': COLORS.success,
    'CONFIRMED': COLORS.success,
    'PENDING': COLORS.warning,
    'CONFLICT': COLORS.danger,
    'UNALLOCATED': COLORS.gray,
    'OVERRIDDEN': COLORS.warning,
  };
  return colorMap[status] || COLORS.gray;
}

function t(text: string, options: any = {}): any {
  return {
    text,
    font: DEFAULT_FONT,
    ...options
  };
}

// ============================================================
// 4. PDF BUILDING BLOCKS
// ============================================================

// Enhanced Header with better styling
function createEnhancedHeader(): any {
  return {
    table: {
      widths: ['*'],
      body: [
        [
          {
            stack: [
              { text: 'EDUALLOC', fontSize: 28, bold: true, color: COLORS.white, font: DEFAULT_FONT },
              { text: 'Course Allocation Management System', fontSize: 11, color: COLORS.white, font: DEFAULT_FONT },
            ],
            fillColor: COLORS.primary,
            margin: [25, 20, 25, 16],
            alignment: 'center',
          },
        ],
      ],
    },
    layout: 'noBorders',
  };
}

// Enhanced Info Card with better styling
function createEnhancedInfoCard(data: {
  generatedAt: string;
  reportType: string;
  generatedBy: string;
  totalRecords: number;
  ref?: string;
  extra?: { label: string; value: string; color?: string }[];
}): any {
  const rows = [
    ['Generated On', `${formatDate(data.generatedAt)} • ${formatTime(data.generatedAt)}`],
    ['Report Type', data.reportType],
    ['Generated By', data.generatedBy],
    ['Total Records', `${data.totalRecords} ${data.reportType.includes('Course') ? 'Courses' : 'Records'}`],
  ];

  if (data.ref) {
    rows.push(['Reference', data.ref]);
  }

  if (data.extra) {
    for (const item of data.extra) {
      rows.push([item.label, { text: item.value, color: item.color || COLORS.grayDark }]);
    }
  }

  return {
    table: {
      widths: ['30%', '70%'],
      body: [
        [
          {
            text: 'REPORT INFORMATION',
            colSpan: 2,
            bold: true,
            fontSize: 13,
            color: COLORS.primary,
            margin: [0, 0, 0, 8],
            font: DEFAULT_FONT,
          },
          {},
        ],
        ...rows.map(row => [
          { 
            text: row[0], 
            bold: true, 
            color: COLORS.secondary, 
            fontSize: 10, 
            font: DEFAULT_FONT,
            margin: [0, 4, 0, 4],
          },
          typeof row[1] === 'string' 
            ? { text: row[1], color: COLORS.grayDark, fontSize: 10, font: DEFAULT_FONT, margin: [0, 4, 0, 4] }
            : { ...row[1], margin: [0, 4, 0, 4] }
        ]),
      ],
    },
    layout: {
      hLineWidth: () => 1,
      hLineColor: () => COLORS.border,
      paddingLeft: () => 8,
      paddingRight: () => 8,
      paddingTop: () => 4,
      paddingBottom: () => 4,
    },
    margin: [0, 0, 0, 20],
  };
}

// Enhanced Stats Cards with better visual design
function createEnhancedStatsCards(stats: { label: string; value: string; color?: string; icon?: string }[]): any {
  return {
    columns: stats.map(stat => ({
      stack: [
        { text: stat.value, fontSize: 22, bold: true, color: stat.color || COLORS.primary, alignment: 'center', font: DEFAULT_FONT },
        { text: stat.label, fontSize: 10, color: COLORS.secondary, alignment: 'center', margin: [0, 4, 0, 0], font: DEFAULT_FONT },
      ],
      fillColor: COLORS.primaryLight,
      padding: [16, 12, 16, 12],
      alignment: 'center',
      margin: [0, 0, 4, 0],
    })),
    columnGap: 8,
    margin: [0, 0, 0, 20],
  };
}

// Enhanced Table with better styling
function createEnhancedTable(
  columns: string[], 
  rows: any[][], 
  columnWidths: string[],
  options?: { 
    headerColor?: string; 
    alternateRowColor?: string;
    rowColors?: (rowIndex: number, data: any) => string;
  }
): any {
  const headerColor = options?.headerColor || COLORS.primary;
  
  const headerRow = columns.map(text => ({
    text: text.toUpperCase(),
    bold: true,
    color: COLORS.white,
    fillColor: headerColor,
    padding: [10, 8, 10, 8],
    fontSize: 9,
    font: DEFAULT_FONT,
    alignment: 'center',
  }));

  return {
    table: {
      headerRows: 1,
      widths: columnWidths,
      body: [
        headerRow,
        ...rows.map((row, rowIndex) => {
          const fillColor = rowIndex % 2 === 0 ? COLORS.grayLighter : COLORS.white;
          return row.map((cell, cellIndex) => ({
            text: cell,
            fontSize: 9,
            padding: [8, 6, 8, 6],
            color: COLORS.grayDark,
            fillColor: options?.rowColors ? options.rowColors(rowIndex, cell) : fillColor,
            font: DEFAULT_FONT,
            alignment: cellIndex === 0 ? 'center' : 'left',
          }));
        })
      ],
    },
    layout: {
      fillColor: (rowIndex: number) => {
        if (rowIndex === 0) return headerColor;
        return rowIndex % 2 === 0 ? COLORS.grayLighter : COLORS.white;
      },
      hLineWidth: (rowIndex: number) => {
        return rowIndex === 0 ? 0 : 0.5;
      },
      hLineColor: () => COLORS.border,
      vLineWidth: () => 0,
    },
    margin: [0, 0, 0, 16],
  };
}

// Enhanced Footer
function createEnhancedFooter(currentPage: number, pageCount: number, ref?: string): any {
  return {
    columns: [
      {
        stack: [
          { text: 'EduAlloc • Course Allocation Management System', fontSize: 8, color: COLORS.secondary, font: DEFAULT_FONT },
          { text: 'Generated for Academic Administration. Confidential PDF Report.', fontSize: 7, color: COLORS.gray, font: DEFAULT_FONT },
        ],
        alignment: 'left',
      },
      {
        stack: [
          { text: ref || '', fontSize: 8, color: COLORS.secondary, font: DEFAULT_FONT, alignment: 'right' },
          { text: `Page ${currentPage} of ${pageCount}`, fontSize: 8, color: COLORS.secondary, font: DEFAULT_FONT, alignment: 'right' },
        ],
        alignment: 'right',
      },
    ],
    margin: [35, 10, 35, 20],
  };
}

// ============================================================
// 5. UTILITY: Standard PDF Generator
// ============================================================

interface PDFOptions {
  title: string;
  subtitle?: string;
  header?: any;
  infoCard: any;
  statsCards: any;
  table: any;
  footerRef?: string;
  extraContent?: any[];
}

function createStandardPDF(options: PDFOptions): any {
  const content = [];
  
  // Header
  content.push(options.header || createEnhancedHeader());
  
  // Title
  content.push({
    text: options.title,
    fontSize: 24,
    bold: true,
    color: COLORS.grayDark,
    alignment: 'center',
    margin: [0, 16, 0, 4],
    font: DEFAULT_FONT,
  });
  
  if (options.subtitle) {
    content.push({
      text: options.subtitle,
      fontSize: 16,
      color: COLORS.primary,
      alignment: 'center',
      margin: [0, 0, 0, 20],
      font: DEFAULT_FONT,
    });
  }
  
  // Info Card
  content.push(options.infoCard);
  
  // Stats Cards
  content.push(options.statsCards);
  
  // Table
  content.push(options.table);
  
  // Extra Content
  if (options.extraContent) {
    content.push(...options.extraContent);
  }
  
  return {
    pageSize: 'A4',
    pageMargins: [35, 55, 35, 55],
    defaultStyle: {
      font: DEFAULT_FONT,
    },
    content,
    footer: (currentPage: number, pageCount: number) => 
      createEnhancedFooter(currentPage, pageCount, options.footerRef),
  };
}

// ============================================================
// 6. REPORT CONTROLLER
// ============================================================
export class ReportController {
  async generateAllocationReport(req: Request, res: Response) {
    try {
      const { lecturerId } = req.body;

      const whereClause: any = {};
      if (lecturerId) {
        whereClause.lecturerId = parseInt(lecturerId);
      }

      const allocations = await prisma.allocation.findMany({
        where: {
          ...whereClause,
          status: { in: ['AUTO_ALLOCATED', 'APPROVED', 'OVERRIDDEN'] }
        },
        include: {
          lecturer: true,
          course: true
        }
      });

      const scores = allocations.map(a => a.score).filter(s => s !== null) as number[];
      const totalScore = scores.reduce((sum, s) => sum + s, 0);
      const avgScore = scores.length > 0 ? (totalScore / scores.length) : 0;
      const highestScore = scores.length > 0 ? Math.max(...scores) : 0;
      const lowestScore = scores.length > 0 ? Math.min(...scores) : 0;

      const reportData = {
        generatedAt: new Date().toISOString(),
        type: 'allocation',
        totalAllocations: allocations.length,
        allocations: allocations.map(a => ({
          lecturer: a.lecturer.name,
          lecturerStaffId: a.lecturer.staffId,
          course: `${a.course.code} - ${a.course.title}`,
          units: a.course.units,
          status: a.status,
          score: a.score
        })),
        avgScore,
        highestScore,
        lowestScore,
      };

      const report = await prisma.report.create({
        data: {
          generatedBy: 'System',
          reportType: 'ALLOCATION_REPORT',
          data: JSON.stringify(reportData)
        }
      });

      return res.json({ success: true, data: report });
    } catch (error) {
      return res.status(500).json({ success: false, error: (error as Error).message });
    }
  }

  // ============================================================
  // LECTURER REPORTS
  // ============================================================
  async generateLecturerReport(req: Request, res: Response) {
    try {
      const lecturerId = parseInt(req.params.id);

      const lecturer = await prisma.lecturer.findUnique({
        where: { id: lecturerId },
        include: {
          allocations: {
            where: {
              status: { in: ['AUTO_ALLOCATED', 'APPROVED', 'OVERRIDDEN'] }
            },
            include: {
              course: true
            }
          }
        }
      });

      if (!lecturer) {
        return res.status(404).json({ success: false, error: 'Lecturer not found' });
      }

      const totalLoad = lecturer.allocations.reduce((sum, a) => sum + a.course.units, 0);
      const utilization = lecturer.maxHours > 0 ? Math.round((totalLoad / lecturer.maxHours) * 100) : 0;

      const reportData = {
        generatedAt: new Date().toISOString(),
        type: 'lecturer_allocation',
        lecturer: {
          name: lecturer.name,
          staffId: lecturer.staffId,
          rank: lecturer.rank,
          email: lecturer.email,
          specialization: lecturer.specialization,
        },
        summary: {
          totalCourses: lecturer.allocations.length,
          totalLoad,
          maxLoad: lecturer.maxHours,
          utilization,
        },
        allocations: lecturer.allocations.map(a => ({
          courseCode: a.course.code,
          courseTitle: a.course.title,
          units: a.course.units,
          level: a.course.level,
          nature: a.course.nature,
          status: a.status,
        })),
      };

      const report = await prisma.report.create({
        data: {
          generatedBy: 'System',
          reportType: 'LECTURER_ALLOCATION_REPORT',
          data: JSON.stringify(reportData)
        }
      });

      return res.json({ success: true, data: report });
    } catch (error) {
      console.error('Error generating lecturer report:', error);
      return res.status(500).json({ success: false, error: (error as Error).message });
    }
  }

  async generateAllLecturerReports(_req: Request, res: Response) {
    try {
      const lecturers = await prisma.lecturer.findMany({
        where: { isActive: true },
        include: {
          allocations: {
            where: {
              status: { in: ['AUTO_ALLOCATED', 'APPROVED', 'OVERRIDDEN'] }
            },
            include: {
              course: true
            }
          }
        }
      });

      const reports = [];
      for (const lecturer of lecturers) {
        const totalLoad = lecturer.allocations.reduce((sum, a) => sum + a.course.units, 0);
        const utilization = lecturer.maxHours > 0 ? Math.round((totalLoad / lecturer.maxHours) * 100) : 0;

        const reportData = {
          generatedAt: new Date().toISOString(),
          type: 'lecturer_allocation',
          lecturer: {
            name: lecturer.name,
            staffId: lecturer.staffId,
            rank: lecturer.rank,
            email: lecturer.email,
            specialization: lecturer.specialization,
          },
          summary: {
            totalCourses: lecturer.allocations.length,
            totalLoad,
            maxLoad: lecturer.maxHours,
            utilization,
          },
          allocations: lecturer.allocations.map(a => ({
            courseCode: a.course.code,
            courseTitle: a.course.title,
            units: a.course.units,
            level: a.course.level,
            nature: a.course.nature,
            status: a.status,
          })),
        };

        const report = await prisma.report.create({
          data: {
            generatedBy: 'System',
            reportType: 'LECTURER_ALLOCATION_REPORT',
            data: JSON.stringify(reportData)
          }
        });

        reports.push({
          lecturerId: lecturer.id,
          lecturerName: lecturer.name,
          lecturerStaffId: lecturer.staffId,
          reportId: report.id,
        });
      }

      return res.json({
        success: true,
        data: {
          totalLecturers: reports.length,
          reports
        }
      });
    } catch (error) {
      console.error('Error generating all lecturer reports:', error);
      return res.status(500).json({ success: false, error: (error as Error).message });
    }
  }

  // ============================================================
  // EXISTING REPORT METHODS
  // ============================================================
  async generateWorkloadSummary(_req: Request, res: Response) {
    try {
      const lecturers = await prisma.lecturer.findMany({
        where: { isActive: true },
        include: {
          allocations: {
            where: {
              status: { in: ['AUTO_ALLOCATED', 'APPROVED', 'OVERRIDDEN'] }
            },
            include: { course: true }
          }
        }
      });

      const summary = lecturers.map(l => {
        const totalLoad = l.allocations.reduce((sum, a) => sum + a.course.units, 0);
        return {
          name: l.name,
          staffId: l.staffId,
          rank: l.rank,
          currentLoad: totalLoad,
          maxLoad: l.maxHours,
          utilization: l.maxHours > 0 ? Math.round((totalLoad / l.maxHours) * 100) : 0,
          courses: l.allocations.map(a => ({
            code: a.course.code,
            title: a.course.title,
            units: a.course.units
          }))
        };
      });

      const loads = summary.map(s => s.currentLoad);
      const totalLecturers = lecturers.length;
      const avgLoad = loads.length > 0 ? (loads.reduce((sum, l) => sum + l, 0) / loads.length) : 0;
      const highestLoad = loads.length > 0 ? Math.max(...loads) : 0;
      const lowestLoad = loads.length > 0 ? Math.min(...loads) : 0;

      const reportData = {
        generatedAt: new Date().toISOString(),
        type: 'workload',
        totalLecturers,
        summary,
        avgLoad,
        highestLoad,
        lowestLoad,
      };

      const report = await prisma.report.create({
        data: {
          generatedBy: 'System',
          reportType: 'WORKLOAD_SUMMARY',
          data: JSON.stringify(reportData)
        }
      });

      return res.json({ success: true, data: report });
    } catch (error) {
      return res.status(500).json({ success: false, error: (error as Error).message });
    }
  }

  async generateLevelBasedList(req: Request, res: Response) {
    try {
      const { level } = req.body;
      const levelNum = parseInt(level);

      const courses = await prisma.course.findMany({
        where: {
          level: levelNum,
          status: true
        },
        include: {
          allocations: {
            where: {
              status: { in: ['AUTO_ALLOCATED', 'APPROVED', 'OVERRIDDEN'] }
            },
            include: { lecturer: true }
          }
        }
      });

      const levelData = courses.map(c => ({
        code: c.code,
        title: c.title,
        units: c.units,
        nature: c.nature,
        allocatedTo: c.allocations.length > 0 ? c.allocations[0].lecturer.name : '--',
        status: c.allocations.length > 0 ? 'ALLOCATED' : 'UNALLOCATED'
      }));

      const totalCourses = courses.length;
      const allocated = levelData.filter(c => c.status === 'ALLOCATED').length;
      const unallocated = levelData.filter(c => c.status === 'UNALLOCATED').length;

      const reportData = {
        generatedAt: new Date().toISOString(),
        type: 'level',
        level: levelNum,
        totalCourses,
        allocated,
        unallocated,
        allocationRate: totalCourses > 0 ? Math.round((allocated / totalCourses) * 100) : 0,
        courses: levelData
      };

      const report = await prisma.report.create({
        data: {
          generatedBy: 'System',
          reportType: 'LEVEL_BASED_LIST',
          data: JSON.stringify(reportData)
        }
      });

      return res.json({ success: true, data: report });
    } catch (error) {
      return res.status(500).json({ success: false, error: (error as Error).message });
    }
  }

  async getAll(_req: Request, res: Response) {
    try {
      const reports = await prisma.report.findMany({
        orderBy: { generatedAt: 'desc' }
      });
      return res.json({ success: true, data: reports });
    } catch (error) {
      return res.status(500).json({ success: false, error: (error as Error).message });
    }
  }

  async getById(req: Request, res: Response) {
    try {
      const id = parseInt(req.params.id);
      const report = await prisma.report.findUnique({
        where: { id }
      });
      if (!report) {
        return res.status(404).json({ success: false, error: 'Report not found' });
      }
      return res.json({ success: true, data: report });
    } catch (error) {
      return res.status(500).json({ success: false, error: (error as Error).message });
    }
  }

  // ============================================================
  // EXPORT TO PDF
  // ============================================================
  async exportToPDF(req: Request, res: Response) {
    try {
      const id = parseInt(req.params.id);
      const report = await prisma.report.findUnique({
        where: { id }
      });
      if (!report) {
        return res.status(404).json({ success: false, error: 'Report not found' });
      }

      const reportData = typeof report.data === 'string' ? JSON.parse(report.data) : report.data;

      let pdfDoc: any;
      let filename: string;

      switch (report.reportType) {
        case 'ALLOCATION_REPORT':
          pdfDoc = this.generateAllocationPDF(reportData);
          filename = `allocation-report-${report.id}.pdf`;
          break;
        case 'WORKLOAD_SUMMARY':
          pdfDoc = this.generateWorkloadPDF(reportData);
          filename = `workload-summary-${report.id}.pdf`;
          break;
        case 'LEVEL_BASED_LIST':
          pdfDoc = this.generateLevelPDF(reportData);
          filename = `level-based-list-${report.id}.pdf`;
          break;
        case 'LECTURER_ALLOCATION_REPORT':
          pdfDoc = this.generateLecturerAllocationPDF(reportData);
          filename = `lecturer-${reportData.lecturer?.staffId || 'report'}-${report.id}.pdf`;
          break;
        default:
          throw new Error(`Unknown report type: ${report.reportType}`);
      }

      const pdfBuffer = await new Promise<Buffer>((resolve) => {
        const pdfDocGenerator = printer.createPdfKitDocument(pdfDoc);
        const chunks: any[] = [];
        pdfDocGenerator.on('data', (chunk) => chunks.push(chunk));
        pdfDocGenerator.on('end', () => {
          resolve(Buffer.concat(chunks));
        });
        pdfDocGenerator.end();
      });

      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
      res.setHeader('Content-Length', pdfBuffer.length);

      return res.send(pdfBuffer);
    } catch (error) {
      console.error('PDF Export Error:', error);
      return res.status(500).json({ success: false, error: (error as Error).message });
    }
  }

  // ============================================================
  // PDF GENERATORS
  // ============================================================

  private generateAllocationPDF(data: any) {
    const tableData = data.allocations.map((a: any, index: number) => {
      const statusText = formatStatus(a.status);
      const statusColor = getStatusColor(a.status);
      
      return [
        String(index + 1).padStart(3, '0'),
        a.lecturer,
        a.lecturerStaffId || '-',
        a.course,
        String(a.units),
        { text: statusText, color: statusColor, bold: true },
        a.score ? a.score.toFixed(2) : '-'
      ];
    });

    return createStandardPDF({
      title: 'COURSE ALLOCATION REPORT',
      subtitle: 'Departmental Ledger',
      infoCard: createEnhancedInfoCard({
        generatedAt: data.generatedAt,
        reportType: 'Allocation Report',
        generatedBy: 'System',
        totalRecords: data.totalAllocations,
        ref: 'EA-CS-2024-0812',
        extra: [
          { label: 'Average Score', value: data.avgScore ? data.avgScore.toFixed(2) + '%' : 'N/A' },
          { label: 'Highest Score', value: data.highestScore ? data.highestScore.toFixed(2) + '%' : 'N/A' },
          { label: 'Lowest Score', value: data.lowestScore ? data.lowestScore.toFixed(2) + '%' : 'N/A' },
        ]
      }),
      statsCards: createEnhancedStatsCards([
        { label: 'Total Allocations', value: String(data.totalAllocations), color: COLORS.primary },
        { label: 'Average Score', value: data.avgScore ? data.avgScore.toFixed(2) + '%' : 'N/A', color: COLORS.success },
        { label: 'Highest Score', value: data.highestScore ? data.highestScore.toFixed(2) + '%' : 'N/A', color: COLORS.warning },
      ]),
      table: createEnhancedTable(
        ['#', 'Lecturer', 'Staff ID', 'Course', 'Units', 'Status', 'Score'],
        tableData,
        ['auto', 'auto', 'auto', '*', 'auto', 'auto', 'auto']
      ),
      footerRef: 'EA-CS-2024-0812',
    });
  }

  private generateLecturerAllocationPDF(data: any) {
    const tableData = data.allocations.map((a: any, index: number) => {
      const statusText = formatStatus(a.status);
      const statusColor = getStatusColor(a.status);
      
      return [
        String(index + 1).padStart(2, '0'),
        a.courseCode,
        a.courseTitle,
        String(a.units),
        String(a.level),
        formatEnum(a.nature),
        { text: statusText, color: statusColor, bold: true }
      ];
    });

    const utilizationColor = data.summary.utilization > 80 ? COLORS.danger :
      data.summary.utilization > 60 ? COLORS.warning : COLORS.success;
    
    const utilizationBgColor = data.summary.utilization > 80 ? COLORS.dangerLight :
      data.summary.utilization > 60 ? COLORS.warningLight : COLORS.successLight;

    return {
      pageSize: 'A4',
      pageMargins: [35, 55, 35, 55],
      defaultStyle: {
        font: DEFAULT_FONT,
      },
      content: [
        createEnhancedHeader(),
        {
          text: 'ALLOCATION REPORT',
          fontSize: 24,
          bold: true,
          color: COLORS.grayDark,
          alignment: 'center',
          margin: [0, 16, 0, 4],
          font: DEFAULT_FONT,
        },
        {
          text: data.lecturer.name,
          fontSize: 16,
          color: COLORS.primary,
          alignment: 'center',
          margin: [0, 0, 0, 20],
          font: DEFAULT_FONT,
        },
        // Profile Information Card
        {
          table: {
            widths: ['40%', '60%'],
            body: [
              [
                {
                  text: 'PROFILE INFORMATION',
                  colSpan: 2,
                  bold: true,
                  fontSize: 12,
                  color: COLORS.primary,
                  margin: [0, 0, 0, 8],
                  font: DEFAULT_FONT,
                },
                {}
              ],
              [
                { text: 'Staff ID:', bold: true, color: COLORS.secondary, fontSize: 10, font: DEFAULT_FONT },
                { text: data.lecturer.staffId || '-', color: COLORS.grayDark, fontSize: 10, font: DEFAULT_FONT },
              ],
              [
                { text: 'Rank:', bold: true, color: COLORS.secondary, fontSize: 10, font: DEFAULT_FONT },
                { text: formatEnum(data.lecturer.rank), color: COLORS.grayDark, fontSize: 10, font: DEFAULT_FONT },
              ],
              [
                { text: 'Email:', bold: true, color: COLORS.secondary, fontSize: 10, font: DEFAULT_FONT },
                { text: data.lecturer.email || '-', color: COLORS.grayDark, fontSize: 10, font: DEFAULT_FONT },
              ],
              [
                { text: 'Specialization:', bold: true, color: COLORS.secondary, fontSize: 10, font: DEFAULT_FONT },
                { text: data.lecturer.specialization || '-', color: COLORS.grayDark, fontSize: 10, font: DEFAULT_FONT },
              ],
            ],
          },
          layout: {
            hLineWidth: () => 0.5,
            hLineColor: () => COLORS.border,
            paddingLeft: () => 8,
            paddingRight: () => 8,
            paddingTop: () => 4,
            paddingBottom: () => 4,
          },
          margin: [0, 0, 0, 20],
        },
        // Enhanced Stats Cards
        {
          columns: [
            {
              stack: [
                { text: String(data.summary.totalCourses), fontSize: 22, bold: true, color: COLORS.primary, alignment: 'center', font: DEFAULT_FONT },
                { text: 'Courses Assigned', fontSize: 10, color: COLORS.secondary, alignment: 'center', font: DEFAULT_FONT },
              ],
              fillColor: COLORS.primaryLight,
              padding: [16, 12, 16, 12],
              alignment: 'center',
            },
            {
              stack: [
                { text: `${data.summary.totalLoad} hrs`, fontSize: 22, bold: true, color: COLORS.success, alignment: 'center', font: DEFAULT_FONT },
                { text: 'Total Workload', fontSize: 10, color: COLORS.secondary, alignment: 'center', font: DEFAULT_FONT },
              ],
              fillColor: COLORS.successLight,
              padding: [16, 12, 16, 12],
              alignment: 'center',
            },
            {
              stack: [
                { text: `${data.summary.maxLoad} hrs`, fontSize: 22, bold: true, color: COLORS.warning, alignment: 'center', font: DEFAULT_FONT },
                { text: 'Max Capacity', fontSize: 10, color: COLORS.secondary, alignment: 'center', font: DEFAULT_FONT },
              ],
              fillColor: COLORS.warningLight,
              padding: [16, 12, 16, 12],
              alignment: 'center',
            },
            {
              stack: [
                { text: `${data.summary.utilization}%`, fontSize: 22, bold: true, color: utilizationColor, alignment: 'center', font: DEFAULT_FONT },
                { text: 'Utilization', fontSize: 10, color: COLORS.secondary, alignment: 'center', font: DEFAULT_FONT },
              ],
              fillColor: utilizationBgColor,
              padding: [16, 12, 16, 12],
              alignment: 'center',
            },
          ],
          columnGap: 8,
          margin: [0, 0, 0, 20],
        },
        // Assigned Courses Table
        {
          text: 'ASSIGNED COURSES',
          fontSize: 14,
          bold: true,
          color: COLORS.grayDark,
          margin: [0, 0, 0, 10],
          font: DEFAULT_FONT,
        },
        createEnhancedTable(
          ['#', 'Course Code', 'Course Title', 'Units', 'Level', 'Nature', 'Status'],
          tableData,
          ['auto', 'auto', '*', 'auto', 'auto', 'auto', 'auto'],
          {
            rowColors: (rowIndex, data) => {
              if (typeof data === 'object' && data.text) {
                if (data.text === 'CONFIRMED') return COLORS.successLight;
                if (data.text === 'PENDING') return COLORS.warningLight;
                if (data.text === 'CONFLICT') return COLORS.dangerLight;
                if (data.text === 'ALLOCATED') return COLORS.successLight;
              }
              return rowIndex % 2 === 0 ? COLORS.grayLighter : COLORS.white;
            }
          }
        ),
        // Signature Section
        {
          columns: [
            {
              stack: [
                { text: '_________________________', fontSize: 10, color: COLORS.grayDark, font: DEFAULT_FONT },
                { text: 'Lecturer Signature', fontSize: 9, color: COLORS.secondary, font: DEFAULT_FONT },
              ],
              alignment: 'center',
              margin: [0, 20, 0, 0],
            },
            {
              stack: [
                { text: '_________________________', fontSize: 10, color: COLORS.grayDark, font: DEFAULT_FONT },
                { text: 'HOD Approval', fontSize: 9, color: COLORS.secondary, font: DEFAULT_FONT },
              ],
              alignment: 'center',
              margin: [0, 20, 0, 0],
            },
          ],
          columnGap: 40,
          margin: [0, 20, 0, 0],
        },
        // Footer note
        {
          text: 'This report shows your current course allocation for the academic session. Please review and confirm your assigned courses.',
          fontSize: 9,
          color: COLORS.secondary,
          alignment: 'center',
          margin: [0, 16, 0, 0],
          font: DEFAULT_FONT,
        },
      ],
      footer: (currentPage: number, pageCount: number) => 
        createEnhancedFooter(currentPage, pageCount, `Ref: ${data.lecturer.staffId || 'N/A'}`),
    };
  }

  private generateWorkloadPDF(data: any) {
    const tableData = data.summary.map((s: any, index: number) => {
      let utilizationColor = COLORS.success;
      if (s.utilization > 80) utilizationColor = COLORS.danger;
      else if (s.utilization > 60) utilizationColor = COLORS.warning;
      
      return [
        String(index + 1).padStart(2, '0'),
        s.name,
        s.staffId,
        formatEnum(s.rank),
        String(s.currentLoad),
        String(s.maxLoad),
        { text: `${s.utilization}%`, color: utilizationColor, bold: s.utilization > 80 }
      ];
    });

    return createStandardPDF({
      title: 'WORKLOAD SUMMARY REPORT',
      subtitle: 'Faculty of Computing & Informatics',
      infoCard: createEnhancedInfoCard({
        generatedAt: data.generatedAt,
        reportType: 'Workload Summary',
        generatedBy: 'System',
        totalRecords: data.totalLecturers,
        ref: 'EA-WS-2024-0021',
        extra: [
          { label: 'Average Load', value: data.avgLoad ? data.avgLoad.toFixed(1) + ' hrs' : 'N/A' },
          { label: 'Highest Load', value: data.highestLoad ? data.highestLoad + ' hrs' : 'N/A' },
          { label: 'Lowest Load', value: data.lowestLoad ? data.lowestLoad + ' hrs' : 'N/A' },
        ]
      }),
      statsCards: createEnhancedStatsCards([
        { label: 'Total Lecturers', value: String(data.totalLecturers), color: COLORS.primary },
        { label: 'Average Load', value: data.avgLoad ? data.avgLoad.toFixed(1) + ' hrs' : 'N/A', color: COLORS.success },
        { label: 'Max Individual Load', value: data.highestLoad ? data.highestLoad + ' hrs' : 'N/A', color: COLORS.warning },
      ]),
      table: createEnhancedTable(
        ['#', 'Lecturer', 'Staff ID', 'Rank', 'Current Load', 'Max Load', 'Utilization'],
        tableData,
        ['auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto']
      ),
      footerRef: 'EA-WS-2024-0021',
      extraContent: [
        {
          text: 'Generated for Academic Administration. Confidential PDF Report.',
          fontSize: 8,
          color: COLORS.secondary,
          alignment: 'center',
          margin: [0, 10, 0, 0],
          font: DEFAULT_FONT,
        },
      ],
    });
  }

  private generateLevelPDF(data: any) {
    const tableData = data.courses.map((c: any, index: number) => {
      const statusText = c.status;
      const statusColor = getStatusColor(c.status);
      
      return [
        String(index + 1).padStart(2, '0'),
        c.code,
        c.title,
        String(c.units),
        formatEnum(c.nature),
        c.allocatedTo,
        { text: statusText, color: statusColor, bold: statusText === 'ALLOCATED' }
      ];
    });

    const allocationRateColor = data.allocationRate > 80 ? COLORS.success : 
                                data.allocationRate > 50 ? COLORS.warning : COLORS.danger;

    return createStandardPDF({
      title: `LEVEL ${data.level} - COURSE LIST`,
      subtitle: 'Faculty of Computing & Informatics',
      infoCard: createEnhancedInfoCard({
        generatedAt: data.generatedAt,
        reportType: `${data.level} Level Course List`,
        generatedBy: 'System',
        totalRecords: data.totalCourses,
        ref: `${data.level}-024`,
        extra: [
          { label: 'Allocated', value: String(data.allocated), color: COLORS.success },
          { label: 'Unallocated', value: String(data.unallocated), color: COLORS.danger },
          { label: 'Allocation Rate', value: `${data.allocationRate}%`, color: allocationRateColor },
        ]
      }),
      statsCards: createEnhancedStatsCards([
        { label: 'Total Courses', value: String(data.totalCourses), color: COLORS.primary },
        { label: 'Allocated', value: String(data.allocated), color: COLORS.success },
        { label: 'Allocation %', value: `${data.allocationRate}%`, color: allocationRateColor },
      ]),
      table: createEnhancedTable(
        ['#', 'Course Code', 'Course Title', 'Units', 'Nature', 'Allocated To', 'Status'],
        tableData,
        ['auto', 'auto', '*', 'auto', 'auto', '*', 'auto']
      ),
      footerRef: `${data.level}-024`,
      extraContent: [
        {
          columns: [
            {
              stack: [
                { text: '_________________________', fontSize: 10, color: COLORS.grayDark, font: DEFAULT_FONT },
                { text: 'HOD, Computer Science', fontSize: 9, color: COLORS.secondary, font: DEFAULT_FONT },
              ],
              alignment: 'center',
              margin: [0, 20, 0, 0],
            },
            {
              stack: [
                { text: '_________________________', fontSize: 10, color: COLORS.grayDark, font: DEFAULT_FONT },
                { text: 'STAMP & DATE', fontSize: 9, color: COLORS.secondary, font: DEFAULT_FONT },
              ],
              alignment: 'center',
              margin: [0, 20, 0, 0],
            },
          ],
          columnGap: 40,
          margin: [0, 10, 0, 0],
        },
        {
          text: 'EduAlloc • Course Allocation Management System',
          fontSize: 8,
          color: COLORS.secondary,
          alignment: 'center',
          margin: [0, 10, 0, 0],
          font: DEFAULT_FONT,
        },
      ],
    });
  }
}