import { ReportType } from '../enums';

export interface IReport {
  id: number;
  generatedBy: string;
  generatedAt: Date;
  reportType: ReportType;
  data: any;
  filePath?: string;
}

export class Report implements IReport {
  constructor(
    public id: number,
    public generatedBy: string,
    public reportType: ReportType,
    public data: any,
    public generatedAt: Date = new Date(),
    public filePath?: string
  ) {}

  hasFile(): boolean {
    return !!this.filePath;
  }

  getSummary(): string {
    switch (this.reportType) {
      case ReportType.ALLOCATION_REPORT:
        return `Allocation report generated by ${this.generatedBy}`;
      case ReportType.WORKLOAD_SUMMARY:
        return `Workload summary generated by ${this.generatedBy}`;
      case ReportType.LEVEL_BASED_LIST:
        return `Level-based list generated by ${this.generatedBy}`;
      default:
        return `Report generated by ${this.generatedBy}`;
    }
  }
}